apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flask-cert
spec:
  secretName: flask-app-tls
  dnsNames:
    - app.lachgarazzeddine.me
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  commonName: app.lachgarazzeddine.me
