apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-app
spec:
  source:
    repoURL: https://github.com/zizo1112/flask-gitops-demo
    path: apps
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
