apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zizo1112/flask-gitops-demo
    targetRevision: main
    path: apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
