apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test-app
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-test-app
  template:
    metadata:
      labels:
        app: k8s-test-app
    spec:
      containers:
        - name: k8s-test-app
          image: azzlachgar99918/k8s-test-app:latest
          ports:
            - containerPort: 6000